### ISSUE TITLE
Project licence

### ISSUE THREAD

**Issue by jibaku** [jessykate/django-survey#1]
There are no license associated with the project, it would be good to add one (GPL or even better BSD)

**Comment by jessykate** [comment]
hi @jibaku, you're right! i'll add a license, the one i like to use is the [AGPL](http://www.gnu.org/licenses/agpl-3.0.html).

**Comment by jibaku** [comment]
Isn't the agpl more about the data rather than the code ?

**Comment by jessykate** [comment]
not AFAIU. it specifically references code.

On Wed, Sep 4, 2013 at 11:00 AM, Fabien Schwob notifications@github.comwrote:

> Isn't the agpl more about the data rather than the code ?
> 
> > hi @jibaku, you're right! i'll add a license, the one i like to use is
> > the AGPL.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jessykate/django-survey/issues/1#issuecomment-23810400
> .

## 

Jessy Kate Schingler
http://jessykate.com
